# ============================================================================
# Copyright (c) 2026, superl8 authors
# SPDX-License-Identifier: BSD-3-Clause
# ============================================================================
"""superl8 — W8A8 DP4A FlashAttention-2 for NVIDIA Volta (sm_70)."""

from .autograd import attn, attn_ref
from .ngram import NgramDraftStore, chain_tree_mask
from .ops import (
    gather_q3k,
    attn_decode_cached,
    attn_decode_cached_i4v,
    attn_fp16_fwd,
    attn_int8_decode,
    attn_int8_fwd,
    attn_int8_tree_verify,
    attn_int8_varlen,
    attn_int8_verify,
    attn_paged_decode_cached,
    attn_paged_decode_k8v3,
    backward_cuda,
    causal_conv1d_silu_decode,
    deltanet_fused_decode,
    gated_rmsnorm_decode,
    deltanet_chunk_fwd,
    deltanet_chunk_int8_fwd,
    deltanet_gated_chunk_fwd,
    deltanet_gated_chunk_h2_fwd,
    deltanet_recurrent_decode,
    deltanet_recurrent_fwd,
    lightning_attn_fwd,
    lightning_attn_int8_fwd,
    grouped_linear_w8a8,
    hello_add,
    linear,
    linear_q2k,
    linear_iq3s,
    linear_iq1s,
    linear_iq2s,
    linear_iq2xs,
    linear_iq2xxs,
    linear_iq4xs,
    linear_iq3xxs,
    linear_q3k,
    linear_q4k,
    linear_q5k,
    linear_q6k,
    linear_tq34s,
    linear_w3a8,
    linear_w4a8,
    linear_w8a8,
    mla_decode_absorb,
    mla_decode_absorb_fp16,
    mla_decode_absorb_int8,
    act_and_mul,
    dit_block,
    quantize_i8_rowwise,
    rmsnorm,
    rope,
    quantize_kv_cache,
    quantize_kv_cache_i4v,
    quantize_kv_write_paged,
)
from .ops import _C  # noqa: F401  (compiled extension, or a CPU-only stand-in)
from .transport import (
    Compressed,
    compress_activation,
    decompress_activation,
    effective_transfer_ms,
    link_speedup,
    reconstruction_report,
)
from .format import FQReader, FQWriter, QTensor, save_superl8

__all__ = [
    "gather_q3k",
    "FQReader",
    "FQWriter",
    "QTensor",
    "save_superl8",
    "NgramDraftStore",
    "chain_tree_mask",
    "Compressed",
    "compress_activation",
    "decompress_activation",
    "effective_transfer_ms",
    "link_speedup",
    "reconstruction_report",
    "attn",
    "attn_ref",
    "attn_decode_cached",
    "attn_decode_cached_i4v",
    "attn_fp16_fwd",
    "attn_int8_decode",
    "attn_int8_fwd",
    "attn_int8_tree_verify",
    "attn_int8_varlen",
    "attn_int8_verify",
    "attn_paged_decode_cached",
    "attn_paged_decode_k8v3",
    "backward_cuda",
    "causal_conv1d_silu_decode",
    "deltanet_fused_decode",
    "gated_rmsnorm_decode",
    "deltanet_chunk_fwd",
    "deltanet_chunk_int8_fwd",
    "deltanet_gated_chunk_fwd",
    "deltanet_gated_chunk_h2_fwd",
    "deltanet_recurrent_decode",
    "deltanet_recurrent_fwd",
    "lightning_attn_fwd",
    "lightning_attn_int8_fwd",
    "grouped_linear_w8a8",
    "hello_add",
    "linear",
    "linear_q2k",
    "linear_iq3s",
    "linear_iq1s",
    "linear_iq2s",
    "linear_iq2xs",
    "linear_iq2xxs",
    "linear_iq4xs",
    "linear_iq3xxs",
    "linear_q3k",
    "linear_q4k",
    "linear_q5k",
    "linear_q6k",
    "linear_tq34s",
    "linear_w3a8",
    "linear_w4a8",
    "linear_w8a8",
    "act_and_mul",
    "dit_block",
    "quantize_i8_rowwise",
    "rmsnorm",
    "rope",
    "mla_decode_absorb",
    "mla_decode_absorb_fp16",
    "mla_decode_absorb_int8",
    "quantize_kv_cache",
    "quantize_kv_cache_i4v",
    "quantize_kv_write_paged",
]
__version__ = "0.1.0"
